# Local config for developer environment.
spring:
  profiles: local
  rabbitmq:
#    addresses: ef102prtrab0v.epi.securitasdirect.local:5672,ef102prtrab0v.epi.securitasdirect.local:5672,ef102prtrab0v.epi.securitasdirect.local:5672
#    username: device-config-consumer
#    password: device-config-consumer-ef
#    virtual-host: device-config   
    addresses: ef102pocmom0v.epi.securitasdirect.local:5672
    username: guest
    password: guest
    virtual-host:       
       
feign:
  url: http://localhost:8081
  client:
    config:
      osbFeignClient:
        #Logger Level: none, basic, headers, full 
        loggerLevel: full

